//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotFrontApplication.HelperClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogHistory
    {
        public int id { get; set; }
        public int User_id { get; set; }
        public System.DateTime LogTime { get; set; }
        public int PasswordEntryAttempts { get; set; }
        public int Success { get; set; }
        public int CountBlockBtn { get; set; }
        public Nullable<System.DateTime> DateBlockBtn { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
