//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotFrontApplication.HelperClass
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbDauevaEntities1 : DbContext
    {
        public DbDauevaEntities1()
            : base("name=DbDauevaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Destination> Destination { get; set; }
        public virtual DbSet<Ns> Ns { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Reject> Reject { get; set; }
        public virtual DbSet<RequestForSending> RequestForSending { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sending> Sending { get; set; }
        public virtual DbSet<Shipment> Shipment { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ValuePrice> ValuePrice { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
    }
}
