//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotFrontApplication.HelperClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reject
    {
        public int id { get; set; }
        public int Shipment_id { get; set; }
        public string Reason { get; set; }
    
        public virtual Shipment Shipment { get; set; }
    }
}
