//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotFrontApplication.HelperClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestForSending
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestForSending()
        {
            this.Sending = new HashSet<Sending>();
        }
    
        public int id { get; set; }
        public int Warehouse_id { get; set; }
        public double Count { get; set; }
        public int Ns_id { get; set; }
        public System.DateTime CollectUpTo { get; set; }
        public Nullable<int> User_id { get; set; }
        public byte Status { get; set; }
    
        public virtual Ns Ns { get; set; }
        public virtual Users Users { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sending> Sending { get; set; }
    }
}
