//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotFrontApplication.HelperClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sending
    {
        public int id { get; set; }
        public int Request_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public System.DateTime Date { get; set; }
        public int Destination_id { get; set; }
        public byte Status { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual RequestForSending RequestForSending { get; set; }
        public virtual Users Users { get; set; }
    }
}
